  | Name    | Type                  | Params
--------------------------------------------------
0 | model   | CLARA                 | 105 M
1 | loss_fn | CLARALoss             | 0
2 | acc_fn  | BidirectionalAccuracy | 0
--------------------------------------------------
105 M     Trainable params
0         Non-trainable params
105 M     Total params
421.919   Total estimated model params size (MB)
Traceback (most recent call last):
  File "C:\Users\PMLS\Documents\BiCLARA-master\clara\train.py", line 93, in <module>
    cli = MyLightningCLI(
          ^^^^^^^^^^^^^^^
  File "C:\Users\PMLS\anaconda3\Lib\site-packages\pytorch_lightning\cli.py", line 386, in __init__
    self._run_subcommand(self.subcommand)
  File "C:\Users\PMLS\anaconda3\Lib\site-packages\pytorch_lightning\cli.py", line 677, in _run_subcommand
    fn(**fn_kwargs)
  File "C:\Users\PMLS\anaconda3\Lib\site-packages\pytorch_lightning\trainer\trainer.py", line 545, in fit
    call._call_and_handle_interrupt(
  File "C:\Users\PMLS\anaconda3\Lib\site-packages\pytorch_lightning\trainer\call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PMLS\anaconda3\Lib\site-packages\pytorch_lightning\trainer\trainer.py", line 581, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "C:\Users\PMLS\anaconda3\Lib\site-packages\pytorch_lightning\trainer\trainer.py", line 990, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\PMLS\anaconda3\Lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1034, in _run_stage
    self._run_sanity_check()
  File "C:\Users\PMLS\anaconda3\Lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1063, in _run_sanity_check
    val_loop.run()
  File "C:\Users\PMLS\anaconda3\Lib\site-packages\pytorch_lightning\loops\utilities.py", line 181, in _decorator
    return loop_run(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PMLS\anaconda3\Lib\site-packages\pytorch_lightning\loops\evaluation_loop.py", line 109, in run
    self.setup_data()
  File "C:\Users\PMLS\anaconda3\Lib\site-packages\pytorch_lightning\loops\evaluation_loop.py", line 165, in setup_data
    dataloaders = _request_dataloader(source)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PMLS\anaconda3\Lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py", line 342, in _request_dataloader
    return data_source.dataloader()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PMLS\anaconda3\Lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py", line 309, in dataloader
    return call._call_lightning_datamodule_hook(self.instance.trainer, self.name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PMLS\anaconda3\Lib\site-packages\pytorch_lightning\trainer\call.py", line 179, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PMLS\Documents\BiCLARA-master\clara\base_tdm.py", line 108, in val_dataloader
    self.valid_dl = self._get_dataloader(self.valid_datapipe, shuffle=False)
                                         ^^^^^^^^^^^^^^^^^^^
AttributeError: 'MultilingualTDM' object has no attribute 'valid_datapipe'
Sanity Checking: |                                                                                                                            | 0/? [00:00<?, ?it/s]